language: node_js
cache:
  directories: node_modules
node_js:
  - "5"

script:
  - npm run lint
  - npm test

notifications:
  slack:
    secure: ssmoeR+BD6CSxOuvdV3m8isfRlcTIkvEJal2c4aQ0deB4rq3vKa0hRGSPtgiGqKtNNe+EvXO3xRUdpKZjyl8SDNLFDgVvq9VwrCGbuRMJcpo63xp5IQWQXlpaQxJGT//vi5tD+CjmK36mTYhGSjqAQxd0Xd67kOMz/UOLB5QN32Zm+PoebvRVQIp+7oNIGXyKGU4QlPx/BJgeYn7/EvU/mu9JqOsm+UE4dzlP8ZBSxGcWrfHtKo1b9Q393Eq3Bib3c2v+gZmXgr4tvYSon8b6A+8IPK3BPVdesholxoCARfmF3tieKWcKDWKHM65ZDiLvRzVJA+BRQYiJFeVW+urMQYgVH6tis9Xpbjt0eP5UD1WWNytq5F2TxQu1ENzUXSeYz4VNY4snyQylejUkBdIhEo2GYe+yzXPGBHHgeTyWh3BO4kC3SCgEngSKQA5AQzT75bdRnGybwEBlCQHsQIjHCPVki/UBDga6TRCKhvYcwi8FTk9ai5IDi3i3BJIKV9EOb1EPHimMBjakFpkjXDczeQ8M/7+ExtwEmMzN2SSjZ1kecg13cykSNvq3pKT4btoZkpvjlNoUREDt8zCIP16+uN+mFk1hMCPZsi6362M/7fNgUBgZWkliEhzJvOn7T2n6DQ6Ad+C/qqs8j0PGicT26+y3QEK8EShspIXdjmIQck=

before_deploy: npm run dist
deploy:
  provider: gcs
  bucket:
    master: blank-intranet
    develop: blank-intranet-test
  local_dir: dist
  upload-dir: employees
  cache_control: "max-age=0"
  acl: public-read
  access_key_id: GOOG7LNU2B5QD5WTPQH7
  secret_access_key:
    secure: riAVaejo/y5jS6CN0ka8H2b18XFdIv/oFL8Z0Z/2frNIWEGVR/G11l8P3MssoWJEmaUoXfrb+nrkm3kg7vEdr5s7TseGYWa37+9rl2hZ4jJO6NAEM4PFOdN+jVhq+Rs/HLWQEu6jZwwOQgbsKleW/loi2m2XYL3TnM00A26f0wNPbzZn31P4Z0wUkKE3G9hu4KgTBjO5SRNKDaMcaq0wM00Hi/2PYj1Nar9cdp0uIBQK3eee2v92Z7MvQQP7fREKqVhvQgdSRaqWUVDCvXlhmv3Wy/lx9q179EB9T/v7m9nbmB86Qg5Rk5ZdlEGDcga6/cL9eCB4zupThopUEPr++gdle75aMabru+gK8oFB2o+b+fEeqzfO0tsZ+EX0dbeJyDueMyZVZlMbbir/zl4hTaCThAu4wR1rKh9qzB0oqAoy6EdltQet7SLsgv3OBwpGo9jzMdWl8ZLDZwAuycjVuqNO6jZphkI676fQZLKXeegUlADwaTctbQ7x69IaID1Da/+V7pEgj9qQk7L75AM6OQZ1XFHj6MA+rVEsLyzwT5tSwaOPB6OeLMTKsf2BgClhTIWnEnZeby8RTELCJF1br8cZUtCkT05bUYRbyr8Jf4f5C9UTNOTA1WkKjpeEVGeNgrP9Xrger9X9EJSLQnZ9K+BRtUUDL0t3qz9P2x81olo=
  skip_cleanup: true
